### ISSUE TITLE
Confused about typing 

### ISSUE THREAD

**Issue by pezholio** [garybernhardt/static-path#9]
Hi, 

I'm trying to create a util that accepts a static-path path, and optionally some arguments to generate a link. I've got this so far:

```typescript
export const linkTo = <Pattern extends string>(
  path: Path<Pattern>,
  {
    text,
    params = {} as Params<Pattern>,
    attributes = {},
    hiddenText = '',
  }: {
    text: string
    params?: Params<Pattern>
    attributes?: Record<string, string>
    hiddenText?: string
  },
): string => {
  let linkBody = text

  if (hiddenText) {
    linkBody = `${linkBody} <span class="govuk-visually-hidden">${hiddenText}</span>`
  }

  const attrBody = Object.keys(attributes)
    .map(a => `${a}=${attributes[a]}`)
    .join(' ')

  return `<a href="${path(params)}" ${attrBody}>${linkBody}</a>`
}
```

Which works like a charm without a link that needs params, i.e:

```
linkTo(path('/foo'), { text: 'Hello' })
```

However, introducing params like so:

```
linkTo(path('/foo/:id'), { text: 'Hello', params: { id: '123' } })
```

Gives me the following typing error:

```
Argument of type 'Path<"/foo/:id">' is not assignable to parameter of type 'Path<string>'.
```

I assume it's something to do with the `Pattern extends string` in the function's generic, but I'm not sure how to proceed. Thoughts welcome!

**Comment by garybernhardt** [comment]
The error goes away if you do this instead:

```typescript
const p = path('/foo/:id')
linkTo(p, { text: 'Hello', params: { id: '123' } })
```

I'm not sure why that is. But the original formulation, where you rewrite the path pattern when calling `linkTo`, wouldn't make much sense anyway. (It's not a static path if you rewrite the pattern every time you link!) So it looks to me like this will probably work out fine in practice.

Unrelated: it looks like your `{} as Params<Patterns>` defeats static typing of the params, and will allow any path to be rendered with no params. I don't know of any way to avoid this problem while also making the params optional, which is why they're not optional in static-path. But I picked up a "don't even try to do this" heuristic about this a few years ago, so maybe it's easier/possible in newer TS versions.

**Comment by pezholio** [comment]
Cool, thanks, and thanks for the great work on this library. FWIW I managed to get it working with this approach:

```typescript
export const linkTo = <Pattern extends `/${string}`>(
  path: Path<Pattern>,
  params: Params<Pattern>,
  {
    text,
    attributes = {},
    hiddenText = '',
  }: {
    text: string
    attributes?: Record<string, string>
    hiddenText?: string
  },
): string => {
  let linkBody = text

  if (hiddenText) {
    linkBody = `${linkBody} <span class="govuk-visually-hidden">${hiddenText}</span>`
  }

  const attrBody = Object.keys(attributes)
    .map(a => `${a}="${attributes[a]}"`)
    .join(' ')

  return `<a href="${path(params)}" ${attrBody}>${linkBody}</a>`
}
```

So making the pattern extend a template starting with a `/` (which a path will always have) seems to have done it! I've also made the params an argument on their own, rather than optional, which definitely seems like a better move 👍

**Comment by garybernhardt** [comment]
Wow, it's very surprising to me that ``Pattern extends `/${string}` `` fixes it, especially given that static-path itself just does `Pattern extends string`. Maybe it's nudging the compiler into a different inference path that gives the right result. In any case, I'm glad that it worked out.
